# Generated by Django 3.2 on 2023-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rengoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='place',
        ),
        migrations.AddField(
            model_name='user',
            name='planet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='拠点'),
        ),
        migrations.DeleteModel(
            name='Planet',
        ),
    ]
